# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Grigore\UIs\MagneticDipoleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DipoleSetupWindow(object):
    def setupUi(self, DipoleSetupWindow):
        DipoleSetupWindow.setObjectName("DipoleSetupWindow")
        DipoleSetupWindow.resize(1400, 786)
        self.centralwidget = QtWidgets.QWidget(DipoleSetupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.FrequencyBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.FrequencyBox.setMinimum(1)
        self.FrequencyBox.setMaximum(250)
        self.FrequencyBox.setObjectName("FrequencyBox")
        self.gridLayout_2.addWidget(self.FrequencyBox, 0, 1, 1, 1)
        self.DisplayParticlesBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.DisplayParticlesBox.setEnabled(False)
        self.DisplayParticlesBox.setMinimum(1)
        self.DisplayParticlesBox.setMaximum(10000)
        self.DisplayParticlesBox.setObjectName("DisplayParticlesBox")
        self.gridLayout_2.addWidget(self.DisplayParticlesBox, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 2, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tfLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.tfLabel_2.setObjectName("tfLabel_2")
        self.gridLayout_4.addWidget(self.tfLabel_2, 1, 1, 1, 1)
        self.TimeStepLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.TimeStepLabel_2.setObjectName("TimeStepLabel_2")
        self.gridLayout_4.addWidget(self.TimeStepLabel_2, 1, 0, 1, 1)
        self.dtEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.dtEntry.setObjectName("dtEntry")
        self.gridLayout_4.addWidget(self.dtEntry, 2, 0, 1, 1)
        self.tfEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tfEntry.setObjectName("tfEntry")
        self.gridLayout_4.addWidget(self.tfEntry, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 10, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.ComputeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ComputeButton.setObjectName("ComputeButton")
        self.verticalLayout_9.addWidget(self.ComputeButton)
        self.AnimateButton = QtWidgets.QPushButton(self.groupBox_5)
        self.AnimateButton.setObjectName("AnimateButton")
        self.verticalLayout_9.addWidget(self.AnimateButton)
        self.gridLayout.addWidget(self.groupBox_5, 7, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.gridLayout.addWidget(self.groupBox_4, 0, 3, 2, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 770, 238))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TwoDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.TwoDButton.setObjectName("TwoDButton")
        self.gridLayout_3.addWidget(self.TwoDButton, 1, 0, 1, 1)
        self.ThreeDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.ThreeDButton.setChecked(True)
        self.ThreeDButton.setObjectName("ThreeDButton")
        self.gridLayout_3.addWidget(self.ThreeDButton, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_4.setObjectName("label_4")
        self.FullTrajectoryButton = QtWidgets.QCheckBox(self.groupBox_6)
        self.FullTrajectoryButton.setGeometry(QtCore.QRect(10, 70, 92, 17))
        self.FullTrajectoryButton.setChecked(True)
        self.FullTrajectoryButton.setObjectName("FullTrajectoryButton")
        self.FigureSizeBox = QtWidgets.QLineEdit(self.groupBox_6)
        self.FigureSizeBox.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.FigureSizeBox.setObjectName("FigureSizeBox")
        self.GridBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.GridBox.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.GridBox.setChecked(True)
        self.GridBox.setObjectName("GridBox")
        self.IntervalBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.IntervalBox.setGeometry(QtCore.QRect(10, 110, 42, 22))
        self.IntervalBox.setMinimum(1)
        self.IntervalBox.setMaximum(100)
        self.IntervalBox.setObjectName("IntervalBox")
        self.gridLayout_3.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.TwoDOptionsBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.TwoDOptionsBox_2.setObjectName("TwoDOptionsBox_2")
        self.CoordinateButton = QtWidgets.QRadioButton(self.TwoDOptionsBox_2)
        self.CoordinateButton.setEnabled(False)
        self.CoordinateButton.setGeometry(QtCore.QRect(60, 20, 111, 17))
        self.CoordinateButton.setObjectName("CoordinateButton")
        self.TwoDOptionGroup = QtWidgets.QButtonGroup(DipoleSetupWindow)
        self.TwoDOptionGroup.setObjectName("TwoDOptionGroup")
        self.TwoDOptionGroup.addButton(self.CoordinateButton)
        self.layoutWidget = QtWidgets.QWidget(self.TwoDOptionsBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 41, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.XYCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XYCheckBox.setEnabled(False)
        self.XYCheckBox.setObjectName("XYCheckBox")
        self.verticalLayout.addWidget(self.XYCheckBox)
        self.XZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XZCheckBox.setEnabled(False)
        self.XZCheckBox.setObjectName("XZCheckBox")
        self.verticalLayout.addWidget(self.XZCheckBox)
        self.YZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.YZCheckBox.setEnabled(False)
        self.YZCheckBox.setObjectName("YZCheckBox")
        self.verticalLayout.addWidget(self.YZCheckBox)
        self.layoutWidget_2 = QtWidgets.QWidget(self.TwoDOptionsBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 140, 101, 19))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckBoxX = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CheckBoxX.setEnabled(False)
        self.CheckBoxX.setObjectName("CheckBoxX")
        self.horizontalLayout_2.addWidget(self.CheckBoxX)
        self.CheckBoxY = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CheckBoxY.setEnabled(False)
        self.CheckBoxY.setObjectName("CheckBoxY")
        self.horizontalLayout_2.addWidget(self.CheckBoxY)
        self.CheckBoxZ = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CheckBoxZ.setEnabled(False)
        self.CheckBoxZ.setObjectName("CheckBoxZ")
        self.horizontalLayout_2.addWidget(self.CheckBoxZ)
        self.layoutWidget_3 = QtWidgets.QWidget(self.TwoDOptionsBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(110, 100, 86, 65))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CoordinatevtButton = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.CoordinatevtButton.setEnabled(False)
        self.CoordinatevtButton.setObjectName("CoordinatevtButton")
        self.TwoDOptionGroup.addButton(self.CoordinatevtButton)
        self.verticalLayout_2.addWidget(self.CoordinatevtButton)
        self.VelocityvtButton = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.VelocityvtButton.setEnabled(False)
        self.VelocityvtButton.setObjectName("VelocityvtButton")
        self.TwoDOptionGroup.addButton(self.VelocityvtButton)
        self.verticalLayout_2.addWidget(self.VelocityvtButton)
        self.PhaseButton = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.PhaseButton.setEnabled(False)
        self.PhaseButton.setObjectName("PhaseButton")
        self.TwoDOptionGroup.addButton(self.PhaseButton)
        self.verticalLayout_2.addWidget(self.PhaseButton)
        self.gridLayout_3.addWidget(self.TwoDOptionsBox_2, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_3, 2, 2, 5, 2)
        self.EFieldLabel = QtWidgets.QLabel(self.centralwidget)
        self.EFieldLabel.setObjectName("EFieldLabel")
        self.gridLayout.addWidget(self.EFieldLabel, 8, 0, 1, 2)
        self.MassLabel = QtWidgets.QLabel(self.centralwidget)
        self.MassLabel.setObjectName("MassLabel")
        self.gridLayout.addWidget(self.MassLabel, 2, 0, 1, 1)
        self.VelocityEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.VelocityEntry.setObjectName("VelocityEntry")
        self.gridLayout.addWidget(self.VelocityEntry, 7, 0, 1, 2)
        self.PositionEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PositionEntry.setObjectName("PositionEntry")
        self.gridLayout.addWidget(self.PositionEntry, 5, 0, 1, 1)
        self.VelLabel = QtWidgets.QLabel(self.centralwidget)
        self.VelLabel.setObjectName("VelLabel")
        self.gridLayout.addWidget(self.VelLabel, 6, 0, 1, 2)
        self.EFieldEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EFieldEntry.setObjectName("EFieldEntry")
        self.gridLayout.addWidget(self.EFieldEntry, 9, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 770, 249))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout.addWidget(self.scrollArea, 9, 2, 3, 2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 595, 89))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.UserInfoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.UserInfoLabel.setObjectName("UserInfoLabel")
        self.verticalLayout_8.addWidget(self.UserInfoLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout.addWidget(self.scrollArea_2, 7, 3, 1, 1)
        self.SetAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetAllButton.setObjectName("SetAllButton")
        self.gridLayout.addWidget(self.SetAllButton, 11, 0, 1, 2)
        self.MassesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MassesEntry.setObjectName("MassesEntry")
        self.gridLayout.addWidget(self.MassesEntry, 3, 0, 1, 2)
        self.ChargesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ChargesEntry.setObjectName("ChargesEntry")
        self.gridLayout.addWidget(self.ChargesEntry, 1, 0, 1, 2)
        self.ChargeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChargeLabel.setObjectName("ChargeLabel")
        self.gridLayout.addWidget(self.ChargeLabel, 0, 0, 1, 1)
        self.PosLabel = QtWidgets.QLabel(self.centralwidget)
        self.PosLabel.setObjectName("PosLabel")
        self.gridLayout.addWidget(self.PosLabel, 4, 0, 1, 1)
        DipoleSetupWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DipoleSetupWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
        self.menubar.setObjectName("menubar")
        DipoleSetupWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DipoleSetupWindow)
        self.statusbar.setObjectName("statusbar")
        DipoleSetupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DipoleSetupWindow)
        QtCore.QMetaObject.connectSlotsByName(DipoleSetupWindow)

    def retranslateUi(self, DipoleSetupWindow):
        _translate = QtCore.QCoreApplication.translate
        DipoleSetupWindow.setWindowTitle(_translate("DipoleSetupWindow", "Setup Window Dipole"))
        self.groupBox_2.setTitle(_translate("DipoleSetupWindow", "Output options"))
        self.label_8.setText(_translate("DipoleSetupWindow", "<html><head/><body><p align=\"center\">Output Frequency</p><p align=\"center\">Steps</p></body></html>"))
        self.FrequencyBox.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Input a positive integer!</p></body></html>"))
        self.label_10.setText(_translate("DipoleSetupWindow", "Particles to show"))
        self.tfLabel_2.setText(_translate("DipoleSetupWindow", "Final time"))
        self.TimeStepLabel_2.setText(_translate("DipoleSetupWindow", "Time-step (s)"))
        self.dtEntry.setPlainText(_translate("DipoleSetupWindow", "5e-3"))
        self.tfEntry.setPlainText(_translate("DipoleSetupWindow", "1e2"))
        self.label_3.setText(_translate("DipoleSetupWindow", "<html><head/><body><p align=\"center\">Click to compute/display</p></body></html>"))
        self.ComputeButton.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Computes the trajectory but <span style=\" font-style:italic; text-decoration: underline;\">does not</span> display it. You need to press the Plot/Animate button to display the plots.</p></body></html>"))
        self.ComputeButton.setText(_translate("DipoleSetupWindow", "Compute Trajectory"))
        self.AnimateButton.setText(_translate("DipoleSetupWindow", "Plot/Animate"))
        self.groupBox_4.setTitle(_translate("DipoleSetupWindow", "Important"))
        self.label_6.setText(_translate("DipoleSetupWindow", "<html><head/><body><p>Try not to exceed 1e8 time steps.</p><p>All inputs <span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">must</span>  be in scientific notation. Don\'t forget to add .0 to integers, i.e. 1.0.</p></body></html>"))
        self.TwoDButton.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.TwoDButton.setText(_translate("DipoleSetupWindow", "2D"))
        self.ThreeDButton.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.ThreeDButton.setText(_translate("DipoleSetupWindow", "3D"))
        self.groupBox_6.setTitle(_translate("DipoleSetupWindow", "Figure Options"))
        self.label_4.setText(_translate("DipoleSetupWindow", "Figure size"))
        self.FullTrajectoryButton.setText(_translate("DipoleSetupWindow", "Full Trajectory"))
        self.FigureSizeBox.setText(_translate("DipoleSetupWindow", "10 7.5"))
        self.GridBox.setText(_translate("DipoleSetupWindow", "Grid on figures"))
        self.TwoDOptionsBox_2.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.TwoDOptionsBox_2.setTitle(_translate("DipoleSetupWindow", "2D Options"))
        self.CoordinateButton.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.CoordinateButton.setText(_translate("DipoleSetupWindow", "Coordinate Space"))
        self.XYCheckBox.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XYCheckBox.setText(_translate("DipoleSetupWindow", "X-Y"))
        self.XZCheckBox.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XZCheckBox.setText(_translate("DipoleSetupWindow", "X-Z"))
        self.YZCheckBox.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.YZCheckBox.setText(_translate("DipoleSetupWindow", "Y-Z"))
        self.CheckBoxX.setText(_translate("DipoleSetupWindow", "X"))
        self.CheckBoxY.setText(_translate("DipoleSetupWindow", "Y"))
        self.CheckBoxZ.setText(_translate("DipoleSetupWindow", "Z"))
        self.CoordinatevtButton.setText(_translate("DipoleSetupWindow", "Coordinate-t"))
        self.VelocityvtButton.setText(_translate("DipoleSetupWindow", "Velocities-t"))
        self.PhaseButton.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.PhaseButton.setText(_translate("DipoleSetupWindow", "Phase Space"))
        self.EFieldLabel.setText(_translate("DipoleSetupWindow", "<html><head/><body><p>Dipole moment value. </p></body></html>"))
        self.MassLabel.setText(_translate("DipoleSetupWindow", "Mass - input a value in Kg in the format \"Value1 Value2 etc.\""))
        self.VelocityEntry.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.VelocityEntry.setPlainText(_translate("DipoleSetupWindow", "0.0 1.0 0.5"))
        self.PositionEntry.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.PositionEntry.setWhatsThis(_translate("DipoleSetupWindow", "<html><head/><body><p>Cat</p></body></html>"))
        self.PositionEntry.setPlainText(_translate("DipoleSetupWindow", "1.0 0.0 0.0"))
        self.VelLabel.setText(_translate("DipoleSetupWindow", "Initial velocities"))
        self.EFieldEntry.setToolTip(_translate("DipoleSetupWindow", "<html><head/><body><p>Remember not to add any semi-colons and to use only one set of values; this is a uniform field!</p></body></html>"))
        self.EFieldEntry.setPlainText(_translate("DipoleSetupWindow", "40.0"))
        self.label_7.setText(_translate("DipoleSetupWindow", "<html><head/><body><p>Welcome to the magnetic dipole simulation.</p><p>Here you can view the trajectories of particles subject</p><p>to a dipolar magnetic field. The dipole is assumed to lie</p><p>along the z-axis. You can choose the charges, masses and dipole moment M,</p><p>Remember that the trajectories are highly dependent on both the product</p><p>qM/m and the starting pitch angle.</p></body></html>"))
        self.UserInfoLabel.setText(_translate("DipoleSetupWindow", "<html><head/><body><p>Status window.</p></body></html>"))
        self.SetAllButton.setText(_translate("DipoleSetupWindow", "Set All"))
        self.MassesEntry.setPlainText(_translate("DipoleSetupWindow", "1.0"))
        self.ChargesEntry.setPlainText(_translate("DipoleSetupWindow", "1.0"))
        self.ChargeLabel.setText(_translate("DipoleSetupWindow", "Charge - input a value in C in the format \"Value1 Value2 etc.\""))
        self.PosLabel.setText(_translate("DipoleSetupWindow", "Initial positions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DipoleSetupWindow = QtWidgets.QMainWindow()
    ui = Ui_DipoleSetupWindow()
    ui.setupUi(DipoleSetupWindow)
    DipoleSetupWindow.show()
    sys.exit(app.exec_())

