# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Grigore\UIs\DriftSetup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DriftSetupWindow(object):
    def setupUi(self, DriftSetupWindow):
        DriftSetupWindow.setObjectName("DriftSetupWindow")
        DriftSetupWindow.resize(1375, 912)
        self.centralwidget = QtWidgets.QWidget(DriftSetupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.ComputeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ComputeButton.setObjectName("ComputeButton")
        self.verticalLayout_4.addWidget(self.ComputeButton)
        self.AnimateButton = QtWidgets.QPushButton(self.groupBox_5)
        self.AnimateButton.setObjectName("AnimateButton")
        self.verticalLayout_4.addWidget(self.AnimateButton)
        self.gridLayout.addWidget(self.groupBox_5, 7, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.FrequencyBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.FrequencyBox.setMinimum(1)
        self.FrequencyBox.setMaximum(250)
        self.FrequencyBox.setObjectName("FrequencyBox")
        self.horizontalLayout.addWidget(self.FrequencyBox)
        self.gridLayout.addWidget(self.groupBox_2, 0, 3, 3, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 582, 358))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 9, 3, 6, 2)
        self.EFieldEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EFieldEntry.setObjectName("EFieldEntry")
        self.gridLayout.addWidget(self.EFieldEntry, 11, 0, 1, 2)
        self.TimeStepLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeStepLabel.setObjectName("TimeStepLabel")
        self.gridLayout.addWidget(self.TimeStepLabel, 12, 0, 1, 1)
        self.EFieldLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.EFieldLabel_2.setObjectName("EFieldLabel_2")
        self.gridLayout.addWidget(self.EFieldLabel_2, 10, 0, 1, 2)
        self.VelocityEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.VelocityEntry.setObjectName("VelocityEntry")
        self.gridLayout.addWidget(self.VelocityEntry, 7, 0, 1, 2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 419, 91))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UserInfoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.UserInfoLabel.setObjectName("UserInfoLabel")
        self.verticalLayout_3.addWidget(self.UserInfoLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 7, 4, 1, 1)
        self.BFieldEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.BFieldEntry.setObjectName("BFieldEntry")
        self.gridLayout.addWidget(self.BFieldEntry, 9, 0, 1, 2)
        self.EFieldLabel = QtWidgets.QLabel(self.centralwidget)
        self.EFieldLabel.setObjectName("EFieldLabel")
        self.gridLayout.addWidget(self.EFieldLabel, 8, 0, 1, 2)
        self.VelLabel = QtWidgets.QLabel(self.centralwidget)
        self.VelLabel.setObjectName("VelLabel")
        self.gridLayout.addWidget(self.VelLabel, 6, 0, 1, 4)
        self.dtEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dtEntry.setObjectName("dtEntry")
        self.gridLayout.addWidget(self.dtEntry, 13, 0, 1, 1)
        self.SetAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetAllButton.setObjectName("SetAllButton")
        self.gridLayout.addWidget(self.SetAllButton, 14, 0, 1, 2)
        self.tfEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tfEntry.setObjectName("tfEntry")
        self.gridLayout.addWidget(self.tfEntry, 13, 1, 1, 1)
        self.tfLabel = QtWidgets.QLabel(self.centralwidget)
        self.tfLabel.setObjectName("tfLabel")
        self.gridLayout.addWidget(self.tfLabel, 12, 1, 1, 1)
        self.MassesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MassesEntry.setObjectName("MassesEntry")
        self.gridLayout.addWidget(self.MassesEntry, 3, 0, 1, 2)
        self.PosLabel = QtWidgets.QLabel(self.centralwidget)
        self.PosLabel.setObjectName("PosLabel")
        self.gridLayout.addWidget(self.PosLabel, 4, 0, 1, 2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 582, 210))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TwoDOptionsBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.TwoDOptionsBox.setEnabled(True)
        self.TwoDOptionsBox.setObjectName("TwoDOptionsBox")
        self.layoutWidget = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 41, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.XYCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XYCheckBox.setEnabled(False)
        self.XYCheckBox.setObjectName("XYCheckBox")
        self.verticalLayout.addWidget(self.XYCheckBox)
        self.XZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XZCheckBox.setEnabled(False)
        self.XZCheckBox.setObjectName("XZCheckBox")
        self.verticalLayout.addWidget(self.XZCheckBox)
        self.YZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.YZCheckBox.setEnabled(False)
        self.YZCheckBox.setObjectName("YZCheckBox")
        self.verticalLayout.addWidget(self.YZCheckBox)
        self.CoordinateButton = QtWidgets.QRadioButton(self.TwoDOptionsBox)
        self.CoordinateButton.setEnabled(False)
        self.CoordinateButton.setGeometry(QtCore.QRect(60, 20, 111, 17))
        self.CoordinateButton.setObjectName("CoordinateButton")
        self.TwoDOptionGroup = QtWidgets.QButtonGroup(DriftSetupWindow)
        self.TwoDOptionGroup.setObjectName("TwoDOptionGroup")
        self.TwoDOptionGroup.addButton(self.CoordinateButton)
        self.widget = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.widget.setGeometry(QtCore.QRect(10, 110, 101, 19))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckBoxX = QtWidgets.QCheckBox(self.widget)
        self.CheckBoxX.setEnabled(False)
        self.CheckBoxX.setObjectName("CheckBoxX")
        self.horizontalLayout_2.addWidget(self.CheckBoxX)
        self.CheckBoxY = QtWidgets.QCheckBox(self.widget)
        self.CheckBoxY.setEnabled(False)
        self.CheckBoxY.setObjectName("CheckBoxY")
        self.horizontalLayout_2.addWidget(self.CheckBoxY)
        self.CheckBoxZ = QtWidgets.QCheckBox(self.widget)
        self.CheckBoxZ.setEnabled(False)
        self.CheckBoxZ.setObjectName("CheckBoxZ")
        self.horizontalLayout_2.addWidget(self.CheckBoxZ)
        self.widget1 = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.widget1.setGeometry(QtCore.QRect(120, 80, 86, 65))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CoordinatevtButton = QtWidgets.QRadioButton(self.widget1)
        self.CoordinatevtButton.setEnabled(False)
        self.CoordinatevtButton.setObjectName("CoordinatevtButton")
        self.TwoDOptionGroup.addButton(self.CoordinatevtButton)
        self.verticalLayout_2.addWidget(self.CoordinatevtButton)
        self.VelocityvtButton = QtWidgets.QRadioButton(self.widget1)
        self.VelocityvtButton.setEnabled(False)
        self.VelocityvtButton.setObjectName("VelocityvtButton")
        self.TwoDOptionGroup.addButton(self.VelocityvtButton)
        self.verticalLayout_2.addWidget(self.VelocityvtButton)
        self.PhaseButton = QtWidgets.QRadioButton(self.widget1)
        self.PhaseButton.setEnabled(False)
        self.PhaseButton.setObjectName("PhaseButton")
        self.TwoDOptionGroup.addButton(self.PhaseButton)
        self.verticalLayout_2.addWidget(self.PhaseButton)
        self.gridLayout_2.addWidget(self.TwoDOptionsBox, 0, 0, 2, 1)
        self.TwoDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.TwoDButton.setObjectName("TwoDButton")
        self.buttonGroup = QtWidgets.QButtonGroup(DriftSetupWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.TwoDButton)
        self.gridLayout_2.addWidget(self.TwoDButton, 2, 0, 1, 1)
        self.ThreeDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.ThreeDButton.setChecked(True)
        self.ThreeDButton.setObjectName("ThreeDButton")
        self.buttonGroup.addButton(self.ThreeDButton)
        self.gridLayout_2.addWidget(self.ThreeDButton, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_3.setObjectName("label_3")
        self.FullTrajectoryButton = QtWidgets.QCheckBox(self.groupBox_3)
        self.FullTrajectoryButton.setGeometry(QtCore.QRect(10, 70, 92, 17))
        self.FullTrajectoryButton.setChecked(True)
        self.FullTrajectoryButton.setObjectName("FullTrajectoryButton")
        self.FigureSizeBox = QtWidgets.QLineEdit(self.groupBox_3)
        self.FigureSizeBox.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.FigureSizeBox.setObjectName("FigureSizeBox")
        self.GridBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.GridBox.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.GridBox.setChecked(True)
        self.GridBox.setObjectName("GridBox")
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 2, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 3, 3, 3, 2)
        self.PositionEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PositionEntry.setObjectName("PositionEntry")
        self.gridLayout.addWidget(self.PositionEntry, 5, 0, 1, 2)
        self.ChargesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ChargesEntry.setObjectName("ChargesEntry")
        self.gridLayout.addWidget(self.ChargesEntry, 1, 0, 1, 2)
        self.MassLabel = QtWidgets.QLabel(self.centralwidget)
        self.MassLabel.setObjectName("MassLabel")
        self.gridLayout.addWidget(self.MassLabel, 2, 0, 1, 2)
        self.ChargeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChargeLabel.setObjectName("ChargeLabel")
        self.gridLayout.addWidget(self.ChargeLabel, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addWidget(self.groupBox, 0, 4, 3, 1)
        DriftSetupWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DriftSetupWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1375, 21))
        self.menubar.setObjectName("menubar")
        DriftSetupWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DriftSetupWindow)
        self.statusbar.setObjectName("statusbar")
        DriftSetupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DriftSetupWindow)
        QtCore.QMetaObject.connectSlotsByName(DriftSetupWindow)

    def retranslateUi(self, DriftSetupWindow):
        _translate = QtCore.QCoreApplication.translate
        DriftSetupWindow.setWindowTitle(_translate("DriftSetupWindow", "Setup Window Drift"))
        self.label.setText(_translate("DriftSetupWindow", "<html><head/><body><p align=\"center\">Click to compute/display</p></body></html>"))
        self.ComputeButton.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Computes the trajectory but <span style=\" font-style:italic; text-decoration: underline;\">does not</span> display it. You need to press the Plot/Animate button to display the plots.</p></body></html>"))
        self.ComputeButton.setText(_translate("DriftSetupWindow", "Compute Trajectory"))
        self.AnimateButton.setText(_translate("DriftSetupWindow", "Plot window"))
        self.groupBox_2.setTitle(_translate("DriftSetupWindow", "Output options"))
        self.label_2.setText(_translate("DriftSetupWindow", "<html><head/><body><p align=\"center\">Output Frequency</p><p align=\"center\">Steps</p></body></html>"))
        self.FrequencyBox.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Input a positive integer!</p></body></html>"))
        self.label_4.setText(_translate("DriftSetupWindow", "<html><head/><body><p>Welcome to the drift motion setup window. </p><p>This simulation uses uniform magnetic <span style=\" font-style:italic;\">and</span> electric fields. </p><p>You can in principle set up any motion which is dictated by such fields.</p><p>The default values correspond to a positron initially at rest.</p><p>Due to the electric field in the x direction, a drift motion is generated.</p><p>The drift velocity is proportional to the ratio between E and B.</p><p>For the default settings it is 100 m/s</p><p><br/></p></body></html>"))
        self.EFieldEntry.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Remember not to add any semi-colons and to use only one set of values; this is a uniform field!</p></body></html>"))
        self.EFieldEntry.setPlainText(_translate("DriftSetupWindow", "5.6812e-6 0.0 0.0"))
        self.TimeStepLabel.setText(_translate("DriftSetupWindow", "Time-step (s)"))
        self.EFieldLabel_2.setText(_translate("DriftSetupWindow", "Electric Field Strength - Use the format \"Ex, Ey,Ez\"; in V/m"))
        self.VelocityEntry.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.VelocityEntry.setPlainText(_translate("DriftSetupWindow", "0.0 0.0 0.0"))
        self.UserInfoLabel.setText(_translate("DriftSetupWindow", "<html><head/><body><p>Status window.</p></body></html>"))
        self.BFieldEntry.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Remember not to add any semi-colons and to use only one set of values; this is a uniform field!</p></body></html>"))
        self.BFieldEntry.setPlainText(_translate("DriftSetupWindow", "0.0 0.0 5.6812e-8"))
        self.EFieldLabel.setText(_translate("DriftSetupWindow", "<html><head/><body><p>Magnetic Field Strength - use Bx, By, Bz; in T</p></body></html>"))
        self.VelLabel.setText(_translate("DriftSetupWindow", "Initial Velocity Input in m/s; use \"vx1, vy1, vz1; vx2, vy2, vz2;...\""))
        self.dtEntry.setPlainText(_translate("DriftSetupWindow", "1e-6"))
        self.SetAllButton.setText(_translate("DriftSetupWindow", "Set All"))
        self.tfEntry.setPlainText(_translate("DriftSetupWindow", "1e-2"))
        self.tfLabel.setText(_translate("DriftSetupWindow", "Final time"))
        self.MassesEntry.setPlainText(_translate("DriftSetupWindow", "9.109e-31"))
        self.PosLabel.setText(_translate("DriftSetupWindow", "Initial Position Input in m; Format \"X1 Y1 Z1; X2 Y2 Z2; ... \" "))
        self.TwoDOptionsBox.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.TwoDOptionsBox.setTitle(_translate("DriftSetupWindow", "2D Options"))
        self.XYCheckBox.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XYCheckBox.setText(_translate("DriftSetupWindow", "X-Y"))
        self.XZCheckBox.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XZCheckBox.setText(_translate("DriftSetupWindow", "X-Z"))
        self.YZCheckBox.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.YZCheckBox.setText(_translate("DriftSetupWindow", "Y-Z"))
        self.CoordinateButton.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.CoordinateButton.setText(_translate("DriftSetupWindow", "Coordinate Space"))
        self.CheckBoxX.setText(_translate("DriftSetupWindow", "X"))
        self.CheckBoxY.setText(_translate("DriftSetupWindow", "Y"))
        self.CheckBoxZ.setText(_translate("DriftSetupWindow", "Z"))
        self.CoordinatevtButton.setText(_translate("DriftSetupWindow", "Coordinate-t"))
        self.VelocityvtButton.setText(_translate("DriftSetupWindow", "Velocities-t"))
        self.PhaseButton.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.PhaseButton.setText(_translate("DriftSetupWindow", "Phase Space"))
        self.TwoDButton.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.TwoDButton.setText(_translate("DriftSetupWindow", "2D"))
        self.ThreeDButton.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.ThreeDButton.setText(_translate("DriftSetupWindow", "3D"))
        self.groupBox_3.setTitle(_translate("DriftSetupWindow", "Figure Options"))
        self.label_3.setText(_translate("DriftSetupWindow", "Figure size"))
        self.FullTrajectoryButton.setText(_translate("DriftSetupWindow", "Full Trajectory"))
        self.FigureSizeBox.setText(_translate("DriftSetupWindow", "10 7.5"))
        self.GridBox.setText(_translate("DriftSetupWindow", "Grid on figures"))
        self.PositionEntry.setToolTip(_translate("DriftSetupWindow", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.PositionEntry.setWhatsThis(_translate("DriftSetupWindow", "<html><head/><body><p>Cat</p></body></html>"))
        self.PositionEntry.setPlainText(_translate("DriftSetupWindow", "0.0 0.0 0.0"))
        self.ChargesEntry.setPlainText(_translate("DriftSetupWindow", "1.602e-19"))
        self.MassLabel.setText(_translate("DriftSetupWindow", "Mass - input a value in Kg in the format \"Value1 Value2 etc.\""))
        self.ChargeLabel.setText(_translate("DriftSetupWindow", "Charge - input a value in C in the format \"Value1 Value2 etc.\""))
        self.groupBox.setTitle(_translate("DriftSetupWindow", "Important"))
        self.label_5.setText(_translate("DriftSetupWindow", "<html><head/><body><p>Try not to exceed 1e8 time steps.</p><p>All inputs <span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">must</span>  be in scientific notation. Don\'t forget to add .0 to integers, i.e. 1.0.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DriftSetupWindow = QtWidgets.QMainWindow()
    ui = Ui_DriftSetupWindow()
    ui.setupUi(DriftSetupWindow)
    DriftSetupWindow.show()
    sys.exit(app.exec_())

