# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Grigore\UIs\SimulationSetUpEField.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UniformElectricSetup(object):
    def setupUi(self, UniformElectricSetup):
        UniformElectricSetup.setObjectName("UniformElectricSetup")
        UniformElectricSetup.resize(975, 658)
        self.centralwidget = QtWidgets.QWidget(UniformElectricSetup)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.EFieldEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EFieldEntry.setObjectName("EFieldEntry")
        self.gridLayout.addWidget(self.EFieldEntry, 11, 0, 1, 2)
        self.TimeStepLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeStepLabel.setObjectName("TimeStepLabel")
        self.gridLayout.addWidget(self.TimeStepLabel, 12, 0, 1, 1)
        self.tfLabel = QtWidgets.QLabel(self.centralwidget)
        self.tfLabel.setObjectName("tfLabel")
        self.gridLayout.addWidget(self.tfLabel, 12, 1, 1, 1)
        self.ChargeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChargeLabel.setObjectName("ChargeLabel")
        self.gridLayout.addWidget(self.ChargeLabel, 0, 0, 1, 2)
        self.ChargesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ChargesEntry.setObjectName("ChargesEntry")
        self.gridLayout.addWidget(self.ChargesEntry, 1, 0, 1, 2)
        self.MassLabel = QtWidgets.QLabel(self.centralwidget)
        self.MassLabel.setObjectName("MassLabel")
        self.gridLayout.addWidget(self.MassLabel, 2, 0, 1, 2)
        self.MassesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MassesEntry.setObjectName("MassesEntry")
        self.gridLayout.addWidget(self.MassesEntry, 3, 0, 2, 2)
        self.PositionEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PositionEntry.setObjectName("PositionEntry")
        self.gridLayout.addWidget(self.PositionEntry, 6, 0, 1, 2)
        self.VelocityEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.VelocityEntry.setObjectName("VelocityEntry")
        self.gridLayout.addWidget(self.VelocityEntry, 8, 0, 2, 2)
        self.PosLabel = QtWidgets.QLabel(self.centralwidget)
        self.PosLabel.setObjectName("PosLabel")
        self.gridLayout.addWidget(self.PosLabel, 5, 0, 1, 2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 419, 126))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.UserInfoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.UserInfoLabel.setObjectName("UserInfoLabel")
        self.verticalLayout_3.addWidget(self.UserInfoLabel)
        self.DebugButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.DebugButton.setEnabled(False)
        self.DebugButton.setText("")
        self.DebugButton.setObjectName("DebugButton")
        self.verticalLayout_3.addWidget(self.DebugButton)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 9, 3, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addWidget(self.groupBox, 0, 3, 3, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.FrequencyBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.FrequencyBox.setMinimum(1)
        self.FrequencyBox.setMaximum(250)
        self.FrequencyBox.setObjectName("FrequencyBox")
        self.horizontalLayout.addWidget(self.FrequencyBox)
        self.gridLayout.addWidget(self.groupBox_2, 0, 2, 3, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.ComputeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ComputeButton.setObjectName("ComputeButton")
        self.verticalLayout_4.addWidget(self.ComputeButton)
        self.AnimateButton = QtWidgets.QPushButton(self.groupBox_5)
        self.AnimateButton.setEnabled(False)
        self.AnimateButton.setObjectName("AnimateButton")
        self.verticalLayout_4.addWidget(self.AnimateButton)
        self.gridLayout.addWidget(self.groupBox_5, 9, 2, 3, 1)
        self.dtEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dtEntry.setObjectName("dtEntry")
        self.gridLayout.addWidget(self.dtEntry, 13, 0, 1, 1)
        self.SetAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetAllButton.setObjectName("SetAllButton")
        self.gridLayout.addWidget(self.SetAllButton, 14, 0, 1, 2)
        self.tfEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tfEntry.setObjectName("tfEntry")
        self.gridLayout.addWidget(self.tfEntry, 13, 1, 1, 1)
        self.EFieldLabel = QtWidgets.QLabel(self.centralwidget)
        self.EFieldLabel.setObjectName("EFieldLabel")
        self.gridLayout.addWidget(self.EFieldLabel, 10, 0, 1, 2)
        self.VelLabel = QtWidgets.QLabel(self.centralwidget)
        self.VelLabel.setObjectName("VelLabel")
        self.gridLayout.addWidget(self.VelLabel, 7, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 582, 223))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ThreeDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.ThreeDButton.setChecked(True)
        self.ThreeDButton.setObjectName("ThreeDButton")
        self.gridLayout_2.addWidget(self.ThreeDButton, 3, 0, 1, 1)
        self.TwoDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.TwoDButton.setObjectName("TwoDButton")
        self.gridLayout_2.addWidget(self.TwoDButton, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_4.setObjectName("label_4")
        self.FullTrajectoryButton = QtWidgets.QCheckBox(self.groupBox_3)
        self.FullTrajectoryButton.setGeometry(QtCore.QRect(10, 70, 92, 17))
        self.FullTrajectoryButton.setChecked(True)
        self.FullTrajectoryButton.setObjectName("FullTrajectoryButton")
        self.FigureSizeBox = QtWidgets.QLineEdit(self.groupBox_3)
        self.FigureSizeBox.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.FigureSizeBox.setObjectName("FigureSizeBox")
        self.GridBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.GridBox.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.GridBox.setChecked(True)
        self.GridBox.setObjectName("GridBox")
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.TwoDOptionsBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.TwoDOptionsBox.setObjectName("TwoDOptionsBox")
        self.layoutWidget = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 41, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.XYCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XYCheckBox.setEnabled(False)
        self.XYCheckBox.setObjectName("XYCheckBox")
        self.verticalLayout.addWidget(self.XYCheckBox)
        self.XZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XZCheckBox.setEnabled(False)
        self.XZCheckBox.setObjectName("XZCheckBox")
        self.verticalLayout.addWidget(self.XZCheckBox)
        self.YZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.YZCheckBox.setEnabled(False)
        self.YZCheckBox.setObjectName("YZCheckBox")
        self.verticalLayout.addWidget(self.YZCheckBox)
        self.CoordinateButton = QtWidgets.QRadioButton(self.TwoDOptionsBox)
        self.CoordinateButton.setEnabled(False)
        self.CoordinateButton.setGeometry(QtCore.QRect(60, 20, 111, 17))
        self.CoordinateButton.setObjectName("CoordinateButton")
        self.TwoDOptionGroup = QtWidgets.QButtonGroup(UniformElectricSetup)
        self.TwoDOptionGroup.setObjectName("TwoDOptionGroup")
        self.TwoDOptionGroup.addButton(self.CoordinateButton)
        self.layoutWidget_2 = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 90, 86, 65))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CoordinatevtButton = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.CoordinatevtButton.setEnabled(False)
        self.CoordinatevtButton.setObjectName("CoordinatevtButton")
        self.TwoDOptionGroup.addButton(self.CoordinatevtButton)
        self.verticalLayout_2.addWidget(self.CoordinatevtButton)
        self.VelocityvtButton = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.VelocityvtButton.setEnabled(False)
        self.VelocityvtButton.setObjectName("VelocityvtButton")
        self.TwoDOptionGroup.addButton(self.VelocityvtButton)
        self.verticalLayout_2.addWidget(self.VelocityvtButton)
        self.PhaseButton = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.PhaseButton.setEnabled(False)
        self.PhaseButton.setObjectName("PhaseButton")
        self.TwoDOptionGroup.addButton(self.PhaseButton)
        self.verticalLayout_2.addWidget(self.PhaseButton)
        self.layoutWidget_3 = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 110, 101, 19))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CheckBoxX = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.CheckBoxX.setEnabled(False)
        self.CheckBoxX.setObjectName("CheckBoxX")
        self.horizontalLayout_3.addWidget(self.CheckBoxX)
        self.CheckBoxY = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.CheckBoxY.setEnabled(False)
        self.CheckBoxY.setObjectName("CheckBoxY")
        self.horizontalLayout_3.addWidget(self.CheckBoxY)
        self.CheckBoxZ = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.CheckBoxZ.setEnabled(False)
        self.CheckBoxZ.setObjectName("CheckBoxZ")
        self.horizontalLayout_3.addWidget(self.CheckBoxZ)
        self.gridLayout_2.addWidget(self.TwoDOptionsBox, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 3, 2, 6, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 565, 131))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 13, 2, 2, 2)
        UniformElectricSetup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UniformElectricSetup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 975, 21))
        self.menubar.setObjectName("menubar")
        self.menuSetup = QtWidgets.QMenu(self.menubar)
        self.menuSetup.setObjectName("menuSetup")
        UniformElectricSetup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UniformElectricSetup)
        self.statusbar.setObjectName("statusbar")
        UniformElectricSetup.setStatusBar(self.statusbar)
        self.actionCommon_Values = QtWidgets.QAction(UniformElectricSetup)
        self.actionCommon_Values.setObjectName("actionCommon_Values")
        self.menuSetup.addAction(self.actionCommon_Values)
        self.menubar.addAction(self.menuSetup.menuAction())

        self.retranslateUi(UniformElectricSetup)
        QtCore.QMetaObject.connectSlotsByName(UniformElectricSetup)

    def retranslateUi(self, UniformElectricSetup):
        _translate = QtCore.QCoreApplication.translate
        UniformElectricSetup.setWindowTitle(_translate("UniformElectricSetup", "Uniform E Field Setup"))
        self.EFieldEntry.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Remember not to add any semi-colons and to use only one set of values; this is a uniform field!</p></body></html>"))
        self.EFieldEntry.setPlainText(_translate("UniformElectricSetup", "0.0 0.0 5.6812e-8"))
        self.TimeStepLabel.setText(_translate("UniformElectricSetup", "Time-step (s)"))
        self.tfLabel.setText(_translate("UniformElectricSetup", "Final time (s)"))
        self.ChargeLabel.setText(_translate("UniformElectricSetup", "Charge - input a value in C in the format \"Value1 Value2 etc.\""))
        self.ChargesEntry.setPlainText(_translate("UniformElectricSetup", "1.602e-19"))
        self.MassLabel.setText(_translate("UniformElectricSetup", "Mass - input a value in Kg in the format \"Value1 Value2 etc.\""))
        self.MassesEntry.setPlainText(_translate("UniformElectricSetup", "9.109e-31"))
        self.PositionEntry.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.PositionEntry.setWhatsThis(_translate("UniformElectricSetup", "<html><head/><body><p>Cat</p></body></html>"))
        self.PositionEntry.setPlainText(_translate("UniformElectricSetup", "0.0 0.0 0.0"))
        self.VelocityEntry.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.VelocityEntry.setPlainText(_translate("UniformElectricSetup", "0.0 0.0 0.0"))
        self.PosLabel.setText(_translate("UniformElectricSetup", "Initial Position Input in m; Format \"X1 Y1 Z1; X2 Y2 Z2; ... \" "))
        self.UserInfoLabel.setText(_translate("UniformElectricSetup", "<html><head/><body><p>Status window.</p></body></html>"))
        self.groupBox.setTitle(_translate("UniformElectricSetup", "Important"))
        self.label_5.setText(_translate("UniformElectricSetup", "<html><head/><body><p>Try not to exceed 1e8 time steps.</p><p>All inputs <span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">must</span>  be in scientific notation. Don\'t forget to add .0 to integers, i.e. 1.0.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("UniformElectricSetup", "Output options"))
        self.label_2.setText(_translate("UniformElectricSetup", "<html><head/><body><p align=\"center\">Output Frequency</p><p align=\"center\">Steps</p></body></html>"))
        self.FrequencyBox.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Input a positive integer!</p></body></html>"))
        self.label.setText(_translate("UniformElectricSetup", "<html><head/><body><p align=\"center\">Click to compute/display</p></body></html>"))
        self.ComputeButton.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Computes the trajectory but <span style=\" font-style:italic; text-decoration: underline;\">does not</span> display it. You need to press the Plot/Animate button to display the plots.</p></body></html>"))
        self.ComputeButton.setText(_translate("UniformElectricSetup", "Compute Trajectory"))
        self.AnimateButton.setText(_translate("UniformElectricSetup", "Plot window"))
        self.dtEntry.setPlainText(_translate("UniformElectricSetup", "1e-2"))
        self.SetAllButton.setText(_translate("UniformElectricSetup", "Set All"))
        self.tfEntry.setPlainText(_translate("UniformElectricSetup", "1.0"))
        self.EFieldLabel.setText(_translate("UniformElectricSetup", "Electric Field Strength - Use the format \"Ex, Ey,Ez\"; in V/m"))
        self.VelLabel.setText(_translate("UniformElectricSetup", "Initial Velocity Input in m/s; use vx, vy, vz"))
        self.ThreeDButton.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.ThreeDButton.setText(_translate("UniformElectricSetup", "3D"))
        self.TwoDButton.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.TwoDButton.setText(_translate("UniformElectricSetup", "2D"))
        self.groupBox_3.setTitle(_translate("UniformElectricSetup", "Figure Options"))
        self.label_4.setText(_translate("UniformElectricSetup", "Figure size"))
        self.FullTrajectoryButton.setText(_translate("UniformElectricSetup", "Full Trajectory"))
        self.FigureSizeBox.setText(_translate("UniformElectricSetup", "10 7.5"))
        self.GridBox.setText(_translate("UniformElectricSetup", "Grid on figures"))
        self.TwoDOptionsBox.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.TwoDOptionsBox.setTitle(_translate("UniformElectricSetup", "2D Options"))
        self.XYCheckBox.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XYCheckBox.setText(_translate("UniformElectricSetup", "X-Y"))
        self.XZCheckBox.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XZCheckBox.setText(_translate("UniformElectricSetup", "X-Z"))
        self.YZCheckBox.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.YZCheckBox.setText(_translate("UniformElectricSetup", "Y-Z"))
        self.CoordinateButton.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.CoordinateButton.setText(_translate("UniformElectricSetup", "Coordinate Space"))
        self.CoordinatevtButton.setText(_translate("UniformElectricSetup", "Coordinate-t"))
        self.VelocityvtButton.setText(_translate("UniformElectricSetup", "Velocities-t"))
        self.PhaseButton.setToolTip(_translate("UniformElectricSetup", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.PhaseButton.setText(_translate("UniformElectricSetup", "Phase Space"))
        self.CheckBoxX.setText(_translate("UniformElectricSetup", "X"))
        self.CheckBoxY.setText(_translate("UniformElectricSetup", "Y"))
        self.CheckBoxZ.setText(_translate("UniformElectricSetup", "Z"))
        self.label_3.setText(_translate("UniformElectricSetup", "<html><head/><body><p>Welcome to the uniform electric field setup.</p><p>The default simulation options correspond to a positron</p><p>initially at rest, moving under an acceleration of 1m/s<span style=\" vertical-align:super;\">2</span>.</p><p>Try to play around with the values and add more particles.</p><p>Check the phase-space plots. </p></body></html>"))
        self.menuSetup.setTitle(_translate("UniformElectricSetup", "Setup"))
        self.actionCommon_Values.setText(_translate("UniformElectricSetup", "Common Values"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UniformElectricSetup = QtWidgets.QMainWindow()
    ui = Ui_UniformElectricSetup()
    ui.setupUi(UniformElectricSetup)
    UniformElectricSetup.show()
    sys.exit(app.exec_())

