# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Grigore\UIs\GradientDriftCartesian.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CartesianDriftSetup(object):
    def setupUi(self, CartesianDriftSetup):
        CartesianDriftSetup.setObjectName("CartesianDriftSetup")
        CartesianDriftSetup.resize(1341, 742)
        self.centralwidget = QtWidgets.QWidget(CartesianDriftSetup)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.VelocityEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.VelocityEntry.setObjectName("VelocityEntry")
        self.gridLayout.addWidget(self.VelocityEntry, 12, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 0, 2, 1)
        self.MassLabel = QtWidgets.QLabel(self.centralwidget)
        self.MassLabel.setObjectName("MassLabel")
        self.gridLayout.addWidget(self.MassLabel, 4, 1, 1, 5)
        self.MassesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MassesEntry.setObjectName("MassesEntry")
        self.gridLayout.addWidget(self.MassesEntry, 5, 1, 2, 1)
        self.EFieldEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EFieldEntry.setObjectName("EFieldEntry")
        self.gridLayout.addWidget(self.EFieldEntry, 14, 1, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 560, 89))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UserInfoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.UserInfoLabel.setObjectName("UserInfoLabel")
        self.verticalLayout_3.addWidget(self.UserInfoLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 12, 7, 1, 1)
        self.ChargeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChargeLabel.setObjectName("ChargeLabel")
        self.gridLayout.addWidget(self.ChargeLabel, 2, 1, 1, 1)
        self.EFieldLabel = QtWidgets.QLabel(self.centralwidget)
        self.EFieldLabel.setObjectName("EFieldLabel")
        self.gridLayout.addWidget(self.EFieldLabel, 13, 1, 1, 1)
        self.PosLabel = QtWidgets.QLabel(self.centralwidget)
        self.PosLabel.setObjectName("PosLabel")
        self.gridLayout.addWidget(self.PosLabel, 8, 1, 1, 4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.ComputeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ComputeButton.setObjectName("ComputeButton")
        self.verticalLayout_4.addWidget(self.ComputeButton)
        self.AnimateButton = QtWidgets.QPushButton(self.groupBox_5)
        self.AnimateButton.setObjectName("AnimateButton")
        self.verticalLayout_4.addWidget(self.AnimateButton)
        self.gridLayout.addWidget(self.groupBox_5, 12, 6, 1, 1)
        self.ChargesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ChargesEntry.setObjectName("ChargesEntry")
        self.gridLayout.addWidget(self.ChargesEntry, 3, 1, 1, 1)
        self.VelLabel = QtWidgets.QLabel(self.centralwidget)
        self.VelLabel.setObjectName("VelLabel")
        self.gridLayout.addWidget(self.VelLabel, 11, 1, 1, 5)
        self.PositionEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PositionEntry.setObjectName("PositionEntry")
        self.gridLayout.addWidget(self.PositionEntry, 9, 1, 2, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 723, 203))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TwoDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.TwoDButton.setObjectName("TwoDButton")
        self.TwoDThreeDGroup = QtWidgets.QButtonGroup(CartesianDriftSetup)
        self.TwoDThreeDGroup.setObjectName("TwoDThreeDGroup")
        self.TwoDThreeDGroup.addButton(self.TwoDButton)
        self.gridLayout_2.addWidget(self.TwoDButton, 2, 0, 1, 1)
        self.ThreeDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.ThreeDButton.setChecked(True)
        self.ThreeDButton.setObjectName("ThreeDButton")
        self.TwoDThreeDGroup.addButton(self.ThreeDButton)
        self.gridLayout_2.addWidget(self.ThreeDButton, 3, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_3.setObjectName("label_3")
        self.FullTrajectoryButton = QtWidgets.QCheckBox(self.groupBox_6)
        self.FullTrajectoryButton.setGeometry(QtCore.QRect(10, 70, 92, 17))
        self.FullTrajectoryButton.setChecked(True)
        self.FullTrajectoryButton.setObjectName("FullTrajectoryButton")
        self.FigureSizeBox = QtWidgets.QLineEdit(self.groupBox_6)
        self.FigureSizeBox.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.FigureSizeBox.setObjectName("FigureSizeBox")
        self.GridBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.GridBox.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.GridBox.setChecked(True)
        self.GridBox.setObjectName("GridBox")
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.TwoDOptionsBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.TwoDOptionsBox.setObjectName("TwoDOptionsBox")
        self.layoutWidget = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 41, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.XYCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XYCheckBox.setEnabled(False)
        self.XYCheckBox.setObjectName("XYCheckBox")
        self.CoordinateGroup = QtWidgets.QButtonGroup(CartesianDriftSetup)
        self.CoordinateGroup.setObjectName("CoordinateGroup")
        self.CoordinateGroup.setExclusive(False)
        self.CoordinateGroup.addButton(self.XYCheckBox)
        self.verticalLayout.addWidget(self.XYCheckBox)
        self.XZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.XZCheckBox.setEnabled(False)
        self.XZCheckBox.setObjectName("XZCheckBox")
        self.CoordinateGroup.addButton(self.XZCheckBox)
        self.verticalLayout.addWidget(self.XZCheckBox)
        self.YZCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.YZCheckBox.setEnabled(False)
        self.YZCheckBox.setObjectName("YZCheckBox")
        self.CoordinateGroup.addButton(self.YZCheckBox)
        self.verticalLayout.addWidget(self.YZCheckBox)
        self.CoordinateButton = QtWidgets.QRadioButton(self.TwoDOptionsBox)
        self.CoordinateButton.setEnabled(False)
        self.CoordinateButton.setGeometry(QtCore.QRect(60, 20, 111, 17))
        self.CoordinateButton.setObjectName("CoordinateButton")
        self.TwoDOptionGroup = QtWidgets.QButtonGroup(CartesianDriftSetup)
        self.TwoDOptionGroup.setObjectName("TwoDOptionGroup")
        self.TwoDOptionGroup.addButton(self.CoordinateButton)
        self.layoutWidget_2 = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 110, 101, 19))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CheckBoxX = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CheckBoxX.setEnabled(False)
        self.CheckBoxX.setObjectName("CheckBoxX")
        self.horizontalLayout_3.addWidget(self.CheckBoxX)
        self.CheckBoxY = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CheckBoxY.setEnabled(False)
        self.CheckBoxY.setObjectName("CheckBoxY")
        self.horizontalLayout_3.addWidget(self.CheckBoxY)
        self.CheckBoxZ = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CheckBoxZ.setEnabled(False)
        self.CheckBoxZ.setObjectName("CheckBoxZ")
        self.horizontalLayout_3.addWidget(self.CheckBoxZ)
        self.layoutWidget_3 = QtWidgets.QWidget(self.TwoDOptionsBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(120, 70, 86, 65))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CoordinatevtButton = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.CoordinatevtButton.setEnabled(False)
        self.CoordinatevtButton.setObjectName("CoordinatevtButton")
        self.TwoDOptionGroup.addButton(self.CoordinatevtButton)
        self.verticalLayout_2.addWidget(self.CoordinatevtButton)
        self.VelocityvtButton = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.VelocityvtButton.setEnabled(False)
        self.VelocityvtButton.setObjectName("VelocityvtButton")
        self.TwoDOptionGroup.addButton(self.VelocityvtButton)
        self.verticalLayout_2.addWidget(self.VelocityvtButton)
        self.PhaseButton = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.PhaseButton.setEnabled(False)
        self.PhaseButton.setObjectName("PhaseButton")
        self.TwoDOptionGroup.addButton(self.PhaseButton)
        self.verticalLayout_2.addWidget(self.PhaseButton)
        self.gridLayout_2.addWidget(self.TwoDOptionsBox, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 4, 6, 8, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tfLabel = QtWidgets.QLabel(self.groupBox_3)
        self.tfLabel.setObjectName("tfLabel")
        self.gridLayout_3.addWidget(self.tfLabel, 1, 1, 1, 1)
        self.TimeStepLabel = QtWidgets.QLabel(self.groupBox_3)
        self.TimeStepLabel.setObjectName("TimeStepLabel")
        self.gridLayout_3.addWidget(self.TimeStepLabel, 1, 0, 1, 1)
        self.dtEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.dtEntry.setObjectName("dtEntry")
        self.gridLayout_3.addWidget(self.dtEntry, 2, 0, 1, 1)
        self.tfEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tfEntry.setObjectName("tfEntry")
        self.gridLayout_3.addWidget(self.tfEntry, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 15, 1, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.FrequencyBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.FrequencyBox.setMinimum(1)
        self.FrequencyBox.setMaximum(250)
        self.FrequencyBox.setObjectName("FrequencyBox")
        self.horizontalLayout.addWidget(self.FrequencyBox)
        self.gridLayout.addWidget(self.groupBox_2, 2, 6, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addWidget(self.groupBox_4, 2, 7, 2, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 723, 232))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 14, 6, 4, 2)
        self.SetAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetAllButton.setObjectName("SetAllButton")
        self.gridLayout.addWidget(self.SetAllButton, 17, 1, 1, 3)
        CartesianDriftSetup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CartesianDriftSetup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1341, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menuSettings)
        self.menuHelp.setObjectName("menuHelp")
        CartesianDriftSetup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CartesianDriftSetup)
        self.statusbar.setObjectName("statusbar")
        CartesianDriftSetup.setStatusBar(self.statusbar)
        self.actionUseful_Values = QtWidgets.QAction(CartesianDriftSetup)
        self.actionUseful_Values.setObjectName("actionUseful_Values")
        self.actionHow_to_use = QtWidgets.QAction(CartesianDriftSetup)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionAbout = QtWidgets.QAction(CartesianDriftSetup)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGrivei = QtWidgets.QAction(CartesianDriftSetup)
        self.actionGrivei.setObjectName("actionGrivei")
        self.actionCyclotron_Frequency_Calculator = QtWidgets.QAction(CartesianDriftSetup)
        self.actionCyclotron_Frequency_Calculator.setObjectName("actionCyclotron_Frequency_Calculator")
        self.menuHelp.addAction(self.actionUseful_Values)
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menuHelp.addAction(self.actionGrivei)
        self.menuHelp.addAction(self.actionCyclotron_Frequency_Calculator)
        self.menuSettings.addAction(self.menuHelp.menuAction())
        self.menuSettings.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(CartesianDriftSetup)
        QtCore.QMetaObject.connectSlotsByName(CartesianDriftSetup)

    def retranslateUi(self, CartesianDriftSetup):
        _translate = QtCore.QCoreApplication.translate
        CartesianDriftSetup.setWindowTitle(_translate("CartesianDriftSetup", "Gradient Drift Simulation"))
        self.VelocityEntry.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.VelocityEntry.setPlainText(_translate("CartesianDriftSetup", "180.0 0.0 0.0"))
        self.MassLabel.setText(_translate("CartesianDriftSetup", "Mass - input a value in Kg in the format \"Value1 Value2 etc.\""))
        self.MassesEntry.setPlainText(_translate("CartesianDriftSetup", "1.0"))
        self.EFieldEntry.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Remember not to add any semi-colons and to use only one set of values; this is a uniform field!</p></body></html>"))
        self.EFieldEntry.setPlainText(_translate("CartesianDriftSetup", "0.0 0.0 0.0 0.0 0.0 0.0 0.0 1000 0.0"))
        self.UserInfoLabel.setText(_translate("CartesianDriftSetup", "<html><head/><body><p>Status window.</p></body></html>"))
        self.ChargeLabel.setText(_translate("CartesianDriftSetup", "Charge - input a value in C in the format \"Value1 Value2 etc.\""))
        self.EFieldLabel.setText(_translate("CartesianDriftSetup", "<html><head/><body><p>Reference strengths for the fields. See the instructions window for a thorough explanation of the field parameters.</p></body></html>"))
        self.PosLabel.setText(_translate("CartesianDriftSetup", "Initial Position Input in m; Format \"X1 Y1 Z1; X2 Y2 Z2; ... \" "))
        self.label.setText(_translate("CartesianDriftSetup", "<html><head/><body><p align=\"center\">Click to compute/display</p></body></html>"))
        self.ComputeButton.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Computes the trajectory but <span style=\" font-style:italic; text-decoration: underline;\">does not</span> display it. You need to press the Plot/Animate button to display the plots.</p></body></html>"))
        self.ComputeButton.setText(_translate("CartesianDriftSetup", "Compute Trajectory"))
        self.AnimateButton.setText(_translate("CartesianDriftSetup", "Plot/Animate"))
        self.ChargesEntry.setPlainText(_translate("CartesianDriftSetup", "1.0"))
        self.VelLabel.setText(_translate("CartesianDriftSetup", "Initial Velocity Input in m/s; use \"vx1, vy1, vz1; vx2, vy2, vz2;...\""))
        self.PositionEntry.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.PositionEntry.setWhatsThis(_translate("CartesianDriftSetup", "<html><head/><body><p>Cat</p></body></html>"))
        self.PositionEntry.setPlainText(_translate("CartesianDriftSetup", "0.0 0.9 0.0"))
        self.TwoDButton.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.TwoDButton.setText(_translate("CartesianDriftSetup", "2D"))
        self.ThreeDButton.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.ThreeDButton.setText(_translate("CartesianDriftSetup", "3D"))
        self.groupBox_6.setTitle(_translate("CartesianDriftSetup", "Figure Options"))
        self.label_3.setText(_translate("CartesianDriftSetup", "Figure size"))
        self.FullTrajectoryButton.setText(_translate("CartesianDriftSetup", "Full Trajectory"))
        self.FigureSizeBox.setText(_translate("CartesianDriftSetup", "10 7.5"))
        self.GridBox.setText(_translate("CartesianDriftSetup", "Grid on figures"))
        self.TwoDOptionsBox.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.TwoDOptionsBox.setTitle(_translate("CartesianDriftSetup", "2D Options"))
        self.XYCheckBox.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XYCheckBox.setText(_translate("CartesianDriftSetup", "X-Y"))
        self.XZCheckBox.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XZCheckBox.setText(_translate("CartesianDriftSetup", "X-Z"))
        self.YZCheckBox.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.YZCheckBox.setText(_translate("CartesianDriftSetup", "Y-Z"))
        self.CoordinateButton.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.CoordinateButton.setText(_translate("CartesianDriftSetup", "Coordinate Space"))
        self.CheckBoxX.setText(_translate("CartesianDriftSetup", "X"))
        self.CheckBoxY.setText(_translate("CartesianDriftSetup", "Y"))
        self.CheckBoxZ.setText(_translate("CartesianDriftSetup", "Z"))
        self.CoordinatevtButton.setText(_translate("CartesianDriftSetup", "Coordinate-t"))
        self.VelocityvtButton.setText(_translate("CartesianDriftSetup", "Velocities-t"))
        self.PhaseButton.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.PhaseButton.setText(_translate("CartesianDriftSetup", "Phase Space"))
        self.tfLabel.setText(_translate("CartesianDriftSetup", "Final time"))
        self.TimeStepLabel.setText(_translate("CartesianDriftSetup", "Time-step (s)"))
        self.dtEntry.setPlainText(_translate("CartesianDriftSetup", "1e-5"))
        self.tfEntry.setPlainText(_translate("CartesianDriftSetup", "1e-1"))
        self.groupBox_2.setTitle(_translate("CartesianDriftSetup", "Output options"))
        self.label_2.setText(_translate("CartesianDriftSetup", "<html><head/><body><p align=\"center\">Output Frequency</p><p align=\"center\">Steps</p></body></html>"))
        self.FrequencyBox.setToolTip(_translate("CartesianDriftSetup", "<html><head/><body><p>Input a positive integer!</p></body></html>"))
        self.groupBox_4.setTitle(_translate("CartesianDriftSetup", "Important"))
        self.label_5.setText(_translate("CartesianDriftSetup", "<html><head/><body><p>Try not to exceed 1e8 time steps.</p><p>All inputs <span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">must</span>  be in scientific notation. Don\'t forget to add .0 to integers, i.e. 1.0.</p></body></html>"))
        self.label_4.setText(_translate("CartesianDriftSetup", "<html><head/><body><p>Welcome to the Gradient drift simulation. This simulation is quite complicated in terms of the field form.</p><p>A gradient exists in the magnetic field. The parameter values are &quot;Bxx, Bxy, Bxz, Byx, Byy, Byz, Bzx, Bzy, Bzz&quot;.</p><p>The field is computed as</p><p>B= (Bxx*x+Bxy*y+Bxz*z, Byx*x+Byy*y+Byz*z, Bzx*x+Bzy*y+Bzz*z).</p><p>By default, Bzy is the only non-zero value. The drift velocity is, in principle, in the direction perpendicular to the field</p><p><span style=\" font-style:italic;\">and</span> the gradient of its absolute value. Therefore, for the default conditions, the drift should be in the x-direction.</p><p><br/></p></body></html>"))
        self.SetAllButton.setText(_translate("CartesianDriftSetup", "Set All"))
        self.menuSettings.setTitle(_translate("CartesianDriftSetup", "Settings"))
        self.menuHelp.setTitle(_translate("CartesianDriftSetup", "Help"))
        self.actionUseful_Values.setText(_translate("CartesianDriftSetup", "Useful Values"))
        self.actionHow_to_use.setText(_translate("CartesianDriftSetup", "How to use"))
        self.actionAbout.setText(_translate("CartesianDriftSetup", "About"))
        self.actionGrivei.setText(_translate("CartesianDriftSetup", "Grivei"))
        self.actionCyclotron_Frequency_Calculator.setText(_translate("CartesianDriftSetup", "Cyclotron Frequency Calculator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CartesianDriftSetup = QtWidgets.QMainWindow()
    ui = Ui_CartesianDriftSetup()
    ui.setupUi(CartesianDriftSetup)
    CartesianDriftSetup.show()
    sys.exit(app.exec_())

