# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Grigore\UIs\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(804, 502)
        MainMenu.setMinimumSize(QtCore.QSize(804, 502))
        MainMenu.setMaximumSize(QtCore.QSize(804, 502))
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.FacultyLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.FacultyLogoLabel.setGeometry(QtCore.QRect(10, 0, 781, 91))
        self.FacultyLogoLabel.setText("")
        self.FacultyLogoLabel.setPixmap(QtGui.QPixmap("./rugr_fse_logoen_rood_rgb.png"))
        self.FacultyLogoLabel.setScaledContents(True)
        self.FacultyLogoLabel.setObjectName("FacultyLogoLabel")
        self.CourseNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.CourseNameLabel.setGeometry(QtCore.QRect(10, 100, 781, 61))
        self.CourseNameLabel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.CourseNameLabel.setObjectName("CourseNameLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(280, 170, 511, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 492, 321))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(5, 166, 271, 291))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.SimSelectionMenu = QtWidgets.QTreeWidget(self.groupBox)
        self.SimSelectionMenu.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SimSelectionMenu.setObjectName("SimSelectionMenu")
        item_0 = QtWidgets.QTreeWidgetItem(self.SimSelectionMenu)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.SimSelectionMenu)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.SimSelectionMenu)
        self.verticalLayout.addWidget(self.SimSelectionMenu)
        self.SetupLauncher = QtWidgets.QPushButton(self.groupBox)
        self.SetupLauncher.setObjectName("SetupLauncher")
        self.verticalLayout.addWidget(self.SetupLauncher)
        self.DebugPush = QtWidgets.QPushButton(self.groupBox)
        self.DebugPush.setObjectName("DebugPush")
        self.verticalLayout.addWidget(self.DebugPush)
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        self.menuA = QtWidgets.QMenu(self.menubar)
        self.menuA.setObjectName("menuA")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainMenu)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainMenu)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtWidgets.QAction(MainMenu)
        self.actionExit.setObjectName("actionExit")
        self.menuA.addSeparator()
        self.menuA.addAction(self.actionAbout)
        self.menuA.addAction(self.actionHelp)
        self.menuA.addAction(self.actionExit)
        self.menubar.addAction(self.menuA.menuAction())

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "SBTV Main Menu"))
        self.CourseNameLabel.setText(_translate("MainMenu", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; font-style:italic; text-decoration: underline;\">Simple Boris Trajectory Viewer</span></p><p align=\"center\"><span style=\" font-size:6pt; font-weight:600; font-style:italic; text-decoration: underline;\">Powered by SBPP</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("MainMenu", "<html><head/><body><p>Welcome to SBTV. </p><p><br/></p><p>This software is meant to help you better understand the particularities of single-particle motion.</p><p><br/></p><p>In order to start, please select one of the simulation topics from the menu on the left.</p><p><br/></p><p>This application was developed by Grigore-Leon Ratiu, under the supervision</p><p> of Dr. Catherine Rigollet, as part of work on his Bachelor Research Project.</p><p><br/></p><p><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("MainMenu", "Simulation Menu"))
        self.label.setText(_translate("MainMenu", "<html><head/><body><p align=\"center\">Select one of the Topics below, then push </p><p align=\"center\">the &quot;Launch&quot; to launch the simulation setup</p></body></html>"))
        self.SimSelectionMenu.headerItem().setText(0, _translate("MainMenu", "Simulations"))
        __sortingEnabled = self.SimSelectionMenu.isSortingEnabled()
        self.SimSelectionMenu.setSortingEnabled(False)
        self.SimSelectionMenu.topLevelItem(0).setText(0, _translate("MainMenu", "Uniform Fields"))
        self.SimSelectionMenu.topLevelItem(0).child(0).setText(0, _translate("MainMenu", "Pure Electric"))
        self.SimSelectionMenu.topLevelItem(0).child(1).setText(0, _translate("MainMenu", "Pure Magnetic"))
        self.SimSelectionMenu.topLevelItem(0).child(2).setText(0, _translate("MainMenu", "Drift Motion"))
        self.SimSelectionMenu.topLevelItem(1).setText(0, _translate("MainMenu", "Non-Uniform Fields"))
        self.SimSelectionMenu.topLevelItem(1).child(0).setText(0, _translate("MainMenu", "Magnetic Null"))
        self.SimSelectionMenu.topLevelItem(1).child(1).setText(0, _translate("MainMenu", "Magnetic Dipole"))
        self.SimSelectionMenu.topLevelItem(1).child(2).setText(0, _translate("MainMenu", "Magnetic Mirror"))
        self.SimSelectionMenu.topLevelItem(1).child(3).setText(0, _translate("MainMenu", "Electromagnet"))
        self.SimSelectionMenu.topLevelItem(1).child(4).setText(0, _translate("MainMenu", "Radial gradient drift"))
        self.SimSelectionMenu.topLevelItem(1).child(5).setText(0, _translate("MainMenu", "Linear gradient drift"))
        self.SimSelectionMenu.topLevelItem(2).setText(0, _translate("MainMenu", "User-defined field"))
        self.SimSelectionMenu.setSortingEnabled(__sortingEnabled)
        self.SetupLauncher.setText(_translate("MainMenu", "Launch"))
        self.DebugPush.setText(_translate("MainMenu", "DebugButton"))
        self.menuA.setTitle(_translate("MainMenu", "Main Menu"))
        self.actionAbout.setText(_translate("MainMenu", "About"))
        self.actionHelp.setText(_translate("MainMenu", "Help"))
        self.actionExit.setText(_translate("MainMenu", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())

