# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Grigore\UIs\ArbitraryFieldSetup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserFieldSetup(object):
    def setupUi(self, UserFieldSetup):
        UserFieldSetup.setObjectName("UserFieldSetup")
        UserFieldSetup.resize(1066, 707)
        self.centralwidget = QtWidgets.QWidget(UserFieldSetup)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MassLabel = QtWidgets.QLabel(self.centralwidget)
        self.MassLabel.setObjectName("MassLabel")
        self.gridLayout.addWidget(self.MassLabel, 3, 1, 1, 1)
        self.ChargeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChargeLabel.setObjectName("ChargeLabel")
        self.gridLayout.addWidget(self.ChargeLabel, 1, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 0, 1, 1)
        self.ChargesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ChargesEntry.setObjectName("ChargesEntry")
        self.gridLayout.addWidget(self.ChargesEntry, 2, 1, 1, 1)
        self.MassesEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MassesEntry.setObjectName("MassesEntry")
        self.gridLayout.addWidget(self.MassesEntry, 4, 1, 1, 1)
        self.PosLabel = QtWidgets.QLabel(self.centralwidget)
        self.PosLabel.setObjectName("PosLabel")
        self.gridLayout.addWidget(self.PosLabel, 5, 1, 1, 1)
        self.VelocityEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.VelocityEntry.setObjectName("VelocityEntry")
        self.gridLayout.addWidget(self.VelocityEntry, 8, 1, 1, 1)
        self.PositionEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PositionEntry.setObjectName("PositionEntry")
        self.gridLayout.addWidget(self.PositionEntry, 6, 1, 1, 1)
        self.VelLabel = QtWidgets.QLabel(self.centralwidget)
        self.VelLabel.setObjectName("VelLabel")
        self.gridLayout.addWidget(self.VelLabel, 7, 1, 1, 1)
        self.EFieldLabel = QtWidgets.QLabel(self.centralwidget)
        self.EFieldLabel.setObjectName("EFieldLabel")
        self.gridLayout.addWidget(self.EFieldLabel, 9, 1, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 419, 89))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.UserInfoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.UserInfoLabel.setObjectName("UserInfoLabel")
        self.verticalLayout_6.addWidget(self.UserInfoLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout.addWidget(self.scrollArea_2, 8, 3, 1, 1)
        self.EFieldEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.EFieldEntry.setObjectName("EFieldEntry")
        self.gridLayout.addWidget(self.EFieldEntry, 10, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 599, 206))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea, 10, 2, 3, 2)
        self.SetAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetAllButton.setObjectName("SetAllButton")
        self.gridLayout.addWidget(self.SetAllButton, 12, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.gridLayout.addWidget(self.groupBox_4, 1, 3, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.FrequencyBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.FrequencyBox.setMinimum(1)
        self.FrequencyBox.setMaximum(250)
        self.FrequencyBox.setObjectName("FrequencyBox")
        self.horizontalLayout_6.addWidget(self.FrequencyBox)
        self.gridLayout.addWidget(self.groupBox_2, 1, 2, 2, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.ComputeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ComputeButton.setObjectName("ComputeButton")
        self.verticalLayout_10.addWidget(self.ComputeButton)
        self.AnimateButton = QtWidgets.QPushButton(self.groupBox_5)
        self.AnimateButton.setObjectName("AnimateButton")
        self.verticalLayout_10.addWidget(self.AnimateButton)
        self.gridLayout.addWidget(self.groupBox_5, 8, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tfLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.tfLabel_2.setObjectName("tfLabel_2")
        self.gridLayout_5.addWidget(self.tfLabel_2, 1, 1, 1, 1)
        self.TimeStepLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.TimeStepLabel_2.setObjectName("TimeStepLabel_2")
        self.gridLayout_5.addWidget(self.TimeStepLabel_2, 1, 0, 1, 1)
        self.dtEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.dtEntry.setObjectName("dtEntry")
        self.gridLayout_5.addWidget(self.dtEntry, 2, 0, 1, 1)
        self.tfEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tfEntry.setObjectName("tfEntry")
        self.gridLayout_5.addWidget(self.tfEntry, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 11, 1, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 582, 203))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TwoDOptionsBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_6)
        self.TwoDOptionsBox_2.setObjectName("TwoDOptionsBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TwoDOptionsBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.XYCheckBox = QtWidgets.QCheckBox(self.TwoDOptionsBox_2)
        self.XYCheckBox.setEnabled(False)
        self.XYCheckBox.setObjectName("XYCheckBox")
        self.verticalLayout_7.addWidget(self.XYCheckBox)
        self.XZCheckBox = QtWidgets.QCheckBox(self.TwoDOptionsBox_2)
        self.XZCheckBox.setEnabled(False)
        self.XZCheckBox.setObjectName("XZCheckBox")
        self.verticalLayout_7.addWidget(self.XZCheckBox)
        self.YZCheckBox = QtWidgets.QCheckBox(self.TwoDOptionsBox_2)
        self.YZCheckBox.setEnabled(False)
        self.YZCheckBox.setObjectName("YZCheckBox")
        self.verticalLayout_7.addWidget(self.YZCheckBox)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 2, 1)
        self.CoordinateButton = QtWidgets.QRadioButton(self.TwoDOptionsBox_2)
        self.CoordinateButton.setEnabled(False)
        self.CoordinateButton.setObjectName("CoordinateButton")
        self.TwoDOptionGroup = QtWidgets.QButtonGroup(UserFieldSetup)
        self.TwoDOptionGroup.setObjectName("TwoDOptionGroup")
        self.TwoDOptionGroup.addButton(self.CoordinateButton)
        self.gridLayout_2.addWidget(self.CoordinateButton, 0, 1, 1, 2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CoordinatevtButton = QtWidgets.QRadioButton(self.TwoDOptionsBox_2)
        self.CoordinatevtButton.setEnabled(False)
        self.CoordinatevtButton.setObjectName("CoordinatevtButton")
        self.TwoDOptionGroup.addButton(self.CoordinatevtButton)
        self.verticalLayout_8.addWidget(self.CoordinatevtButton)
        self.VelocityvtButton = QtWidgets.QRadioButton(self.TwoDOptionsBox_2)
        self.VelocityvtButton.setEnabled(False)
        self.VelocityvtButton.setObjectName("VelocityvtButton")
        self.TwoDOptionGroup.addButton(self.VelocityvtButton)
        self.verticalLayout_8.addWidget(self.VelocityvtButton)
        self.PhaseButton = QtWidgets.QRadioButton(self.TwoDOptionsBox_2)
        self.PhaseButton.setEnabled(False)
        self.PhaseButton.setObjectName("PhaseButton")
        self.TwoDOptionGroup.addButton(self.PhaseButton)
        self.verticalLayout_8.addWidget(self.PhaseButton)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 1, 2, 2, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CheckBoxX = QtWidgets.QCheckBox(self.TwoDOptionsBox_2)
        self.CheckBoxX.setEnabled(False)
        self.CheckBoxX.setObjectName("CheckBoxX")
        self.horizontalLayout_5.addWidget(self.CheckBoxX)
        self.CheckBoxY = QtWidgets.QCheckBox(self.TwoDOptionsBox_2)
        self.CheckBoxY.setEnabled(False)
        self.CheckBoxY.setObjectName("CheckBoxY")
        self.horizontalLayout_5.addWidget(self.CheckBoxY)
        self.CheckBoxZ = QtWidgets.QCheckBox(self.TwoDOptionsBox_2)
        self.CheckBoxZ.setEnabled(False)
        self.CheckBoxZ.setObjectName("CheckBoxZ")
        self.horizontalLayout_5.addWidget(self.CheckBoxZ)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.TwoDOptionsBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_6)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.FileLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.FileLineEdit.setObjectName("FileLineEdit")
        self.horizontalLayout.addWidget(self.FileLineEdit)
        self.BrowseButton = QtWidgets.QPushButton(self.groupBox)
        self.BrowseButton.setObjectName("BrowseButton")
        self.horizontalLayout.addWidget(self.BrowseButton)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 2, 1)
        self.TwoDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.TwoDButton.setObjectName("TwoDButton")
        self.gridLayout_4.addWidget(self.TwoDButton, 3, 1, 1, 1)
        self.ThreeDButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.ThreeDButton.setChecked(True)
        self.ThreeDButton.setObjectName("ThreeDButton")
        self.gridLayout_4.addWidget(self.ThreeDButton, 2, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_6)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_7.setObjectName("label_7")
        self.FullTrajectoryButton = QtWidgets.QCheckBox(self.groupBox_7)
        self.FullTrajectoryButton.setGeometry(QtCore.QRect(10, 70, 92, 17))
        self.FullTrajectoryButton.setChecked(True)
        self.FullTrajectoryButton.setObjectName("FullTrajectoryButton")
        self.FigureSizeBox = QtWidgets.QLineEdit(self.groupBox_7)
        self.FigureSizeBox.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.FigureSizeBox.setObjectName("FigureSizeBox")
        self.GridBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.GridBox.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.GridBox.setChecked(True)
        self.GridBox.setObjectName("GridBox")
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout.addWidget(self.scrollArea_3, 3, 2, 5, 2)
        UserFieldSetup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserFieldSetup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 21))
        self.menubar.setObjectName("menubar")
        UserFieldSetup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserFieldSetup)
        self.statusbar.setObjectName("statusbar")
        UserFieldSetup.setStatusBar(self.statusbar)

        self.retranslateUi(UserFieldSetup)
        QtCore.QMetaObject.connectSlotsByName(UserFieldSetup)

    def retranslateUi(self, UserFieldSetup):
        _translate = QtCore.QCoreApplication.translate
        UserFieldSetup.setWindowTitle(_translate("UserFieldSetup", "User Defined Field Setup"))
        self.MassLabel.setText(_translate("UserFieldSetup", "Mass - input a value in Kg in the format \"Value1 Value2 etc.\""))
        self.ChargeLabel.setText(_translate("UserFieldSetup", "Charge - input a value in C in the format \"Value1 Value2 etc.\""))
        self.ChargesEntry.setPlainText(_translate("UserFieldSetup", "1.0"))
        self.MassesEntry.setPlainText(_translate("UserFieldSetup", "1.0"))
        self.PosLabel.setText(_translate("UserFieldSetup", "Initial Position Input in m; Format \"X1 Y1 Z1; X2 Y2 Z2; ... \" "))
        self.VelocityEntry.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.VelocityEntry.setPlainText(_translate("UserFieldSetup", "0.0 1e4 0.0"))
        self.PositionEntry.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Remember not to add a semi-colon (;) after the last set of co-ordinates!</p></body></html>"))
        self.PositionEntry.setWhatsThis(_translate("UserFieldSetup", "<html><head/><body><p>Cat</p></body></html>"))
        self.PositionEntry.setPlainText(_translate("UserFieldSetup", "0.0 0.0 0.0"))
        self.VelLabel.setText(_translate("UserFieldSetup", "Initial Velocity Input in m/s; use \"vx1, vy1, vz1; vx2, vy2, vz2;...\""))
        self.EFieldLabel.setText(_translate("UserFieldSetup", "<html><head/><body><p>Function parameters - fparams in your user-defined function</p></body></html>"))
        self.UserInfoLabel.setText(_translate("UserFieldSetup", "<html><head/><body><p>Status window.</p></body></html>"))
        self.EFieldEntry.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Remember not to add any semi-colons and to use only one set of values; this is a uniform field!</p></body></html>"))
        self.EFieldEntry.setPlainText(_translate("UserFieldSetup", "3.14"))
        self.label_6.setText(_translate("UserFieldSetup", "<html><head/><body><p>Welcome to the setup for user-defined fields.</p><p>Here you can set up and visualize a simulation of particle trajectories in EM fields which you define yourself!</p><p>Instructions:</p><p>Write a short .py file called &quot;SBTVUserFields.py&quot; where you define two functions:</p><p>E_func_user(q,t,fparams) and B_func_user(q,t,fparams). You MUST import numpy and you MUST</p><p>import jit and njit from numba. You MUST decorate the functions with &quot;@njit&quot;. An example file has been</p><p>provided with the application.</p><p>After you wrote the file, use the file browsing dialog to select it, then use the &quot;Set All&quot; button and then proceed as usual.</p></body></html>"))
        self.SetAllButton.setText(_translate("UserFieldSetup", "Set All"))
        self.groupBox_4.setTitle(_translate("UserFieldSetup", "Important"))
        self.label_9.setText(_translate("UserFieldSetup", "<html><head/><body><p>Try not to exceed 1e8 time steps.</p><p>All inputs <span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">must</span>  be in scientific notation. Don\'t forget to add .0 to integers, i.e. 1.0.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("UserFieldSetup", "Output options"))
        self.label_8.setText(_translate("UserFieldSetup", "<html><head/><body><p align=\"center\">Output Frequency</p><p align=\"center\">Steps</p></body></html>"))
        self.FrequencyBox.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Input a positive integer!</p></body></html>"))
        self.label_10.setText(_translate("UserFieldSetup", "<html><head/><body><p align=\"center\">Click to compute/display</p></body></html>"))
        self.ComputeButton.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Computes the trajectory but <span style=\" font-style:italic; text-decoration: underline;\">does not</span> display it. You need to press the Plot/Animate button to display the plots.</p></body></html>"))
        self.ComputeButton.setText(_translate("UserFieldSetup", "Compute Trajectory"))
        self.AnimateButton.setText(_translate("UserFieldSetup", "Plot/Animate"))
        self.tfLabel_2.setText(_translate("UserFieldSetup", "Final time"))
        self.TimeStepLabel_2.setText(_translate("UserFieldSetup", "Time-step (s)"))
        self.dtEntry.setPlainText(_translate("UserFieldSetup", "1e-4"))
        self.tfEntry.setPlainText(_translate("UserFieldSetup", "1e1"))
        self.TwoDOptionsBox_2.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.TwoDOptionsBox_2.setTitle(_translate("UserFieldSetup", "2D Options"))
        self.XYCheckBox.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XYCheckBox.setText(_translate("UserFieldSetup", "X-Y"))
        self.XZCheckBox.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.XZCheckBox.setText(_translate("UserFieldSetup", "X-Z"))
        self.YZCheckBox.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select which coordinate pairs you want displayed. Select at least one option.</p></body></html>"))
        self.YZCheckBox.setText(_translate("UserFieldSetup", "Y-Z"))
        self.CoordinateButton.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.CoordinateButton.setText(_translate("UserFieldSetup", "Coordinate Space"))
        self.CoordinatevtButton.setText(_translate("UserFieldSetup", "Coordinate-t"))
        self.VelocityvtButton.setText(_translate("UserFieldSetup", "Velocities-t"))
        self.PhaseButton.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select whether you want to see coordinate space of phase space plots</p></body></html>"))
        self.PhaseButton.setText(_translate("UserFieldSetup", "Phase Space"))
        self.CheckBoxX.setText(_translate("UserFieldSetup", "X"))
        self.CheckBoxY.setText(_translate("UserFieldSetup", "Y"))
        self.CheckBoxZ.setText(_translate("UserFieldSetup", "Z"))
        self.label.setText(_translate("UserFieldSetup", "Field File"))
        self.BrowseButton.setText(_translate("UserFieldSetup", "Browse"))
        self.TwoDButton.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.TwoDButton.setText(_translate("UserFieldSetup", "2D"))
        self.ThreeDButton.setToolTip(_translate("UserFieldSetup", "<html><head/><body><p>Select whether you want to see 2D or 3D plots</p></body></html>"))
        self.ThreeDButton.setText(_translate("UserFieldSetup", "3D"))
        self.groupBox_7.setTitle(_translate("UserFieldSetup", "Figure Options"))
        self.label_7.setText(_translate("UserFieldSetup", "Figure size"))
        self.FullTrajectoryButton.setText(_translate("UserFieldSetup", "Full Trajectory"))
        self.FigureSizeBox.setText(_translate("UserFieldSetup", "10 7.5"))
        self.GridBox.setText(_translate("UserFieldSetup", "Grid on figures"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserFieldSetup = QtWidgets.QMainWindow()
    ui = Ui_UserFieldSetup()
    ui.setupUi(UserFieldSetup)
    UserFieldSetup.show()
    sys.exit(app.exec_())

